FROM python:3.13-slim

WORKDIR /app

COPY requirements-fastapi.txt /app/requirements-fastapi.txt

RUN pip install --no-cache-dir --no-compile -r /app/requirements-fastapi.txt

COPY app/ /app/app/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
